-- Se ejecuta al iniciar, tanto en instalaciones nuevas como existentes.
-- La lista inicia vacía: cada seguimiento requiere un alta explícita.
DO $$
BEGIN
  PERFORM pg_advisory_xact_lock(20260917, 1);
  IF to_regclass('public.seguimiento_diario') IS NULL THEN
    CREATE TABLE seguimiento_diario (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      id_radicado_publico bigint NOT NULL REFERENCES expediente_radicado_publico(id),
      modalidad text NOT NULL CHECK (modalidad IN ('manual', 'automatica')),
      desde date NOT NULL DEFAULT (now() AT TIME ZONE 'America/Bogota')::date,
      hasta date,
      id_usuario bigint REFERENCES users(id),
      id_usuario_retiro bigint REFERENCES users(id),
      CHECK (hasta IS NULL OR hasta >= desde)
    );
    CREATE UNIQUE INDEX seguimiento_diario_activo ON seguimiento_diario(id_radicado_publico) WHERE hasta IS NULL;
  END IF;
  -- Retira únicamente las altas implícitas de la versión anterior.
  -- Las altas de usuarios y todas las constancias se conservan.
  UPDATE seguimiento_diario SET hasta = GREATEST(desde, (now() AT TIME ZONE 'America/Bogota')::date)
    WHERE id_usuario IS NULL AND hasta IS NULL;
END $$;
